/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -Tk chair.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Chair_part_2001" geometry={nodes.Chair_part_2001.geometry} material={materials['Material #32']} position={[0, 4.51, 0]} scale={0.05} />
    </group>
  )
}

useGLTF.preload('/chair-transformed.glb')
