/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -Tk crate.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/crate-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty003" position={[0, 2.53, -1.55]} rotation={[-0.7, 0, 0]}>
          <group name="Empty002" rotation={[0.7, 0, 0]}>
            <mesh name="Crate011" geometry={nodes.Crate011.geometry} material={materials['Material.015']} position={[0, -2.53, 1.55]} />
            <mesh name="Crate012" geometry={nodes.Crate012.geometry} material={materials['Material.014']} position={[0, -2.53, 1.55]} />
            <mesh name="Crate013" geometry={nodes.Crate013.geometry} material={materials['Material.013']} position={[0, -2.53, 1.55]} />
            <mesh name="Crate014" geometry={nodes.Crate014.geometry} material={materials['Material.012']} position={[0, -2.53, 1.55]} />
            <mesh name="Crate015" geometry={nodes.Crate015.geometry} material={materials['Material.014']} position={[0, -2.53, 1.55]} />
          </group>
        </group>
        <mesh name="Crate016" geometry={nodes.Crate016.geometry} material={materials['Material.013']} />
        <mesh name="Crate017" geometry={nodes.Crate017.geometry} material={materials['Material.012']} />
        <mesh name="Crate018" geometry={nodes.Crate018.geometry} material={materials['Material.014']} />
        <mesh name="Crate019" geometry={nodes.Crate019.geometry} material={materials['Material.015']} />
        <mesh name="Curve020" geometry={nodes.Curve020.geometry} material={materials['Material.017']} />
      </group>
    </group>
  )
}

useGLTF.preload('/crate-transformed.glb')
