/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -Tk giftBox.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/giftBox-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Giftbox01" position={[-19.21, 1.06, -18.29]}>
        <mesh name="Cube086" geometry={nodes.Cube086.geometry} material={materials.Pink01} />
        <mesh name="Cube086_1" geometry={nodes.Cube086_1.geometry} material={materials.Pink02} />
        <mesh name="Cube086_2" geometry={nodes.Cube086_2.geometry} material={materials.Pink03} />
        <mesh name="Cube086_3" geometry={nodes.Cube086_3.geometry} material={materials.Yellow01} />
      </group>
    </group>
  )
}

useGLTF.preload('/giftBox-transformed.glb')
