/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 hq-v19.glb -Tk
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hq-v19-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="table_base" geometry={nodes.table_base.geometry} material={materials['main-metal-reflective']} position={[0.42, -0.09, -7.02]} />
      <mesh name="table001" geometry={nodes.table001.geometry} material={materials['display Table']} position={[0.42, -0.09, -7.02]} />
      <mesh name="light-plane" geometry={nodes['light-plane'].geometry} material={materials.top_light} />
      <mesh name="outer_plate" geometry={nodes.outer_plate.geometry} material={materials['main-metal-reflective']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="table" geometry={nodes.table.geometry} material={materials['main-metal-reflective']} position={[0, 4.87, 0]} />
      <mesh name="center-lamp" geometry={nodes['center-lamp'].geometry} material={materials['main-metal-reflective']} />
      <mesh name="outer-structure" geometry={nodes['outer-structure'].geometry} material={materials['main-metal-reflective']} />
      <group name="cake-slice-decoration" rotation={[0, -1.31, 0]}>
        <mesh name="Mesh082" geometry={nodes.Mesh082.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh082_1" geometry={nodes.Mesh082_1.geometry} material={materials.white_ambient_light} />
      </group>
      <group name="cake-slice-decoration001" rotation={[0, -0.05, 0]}>
        <mesh name="Mesh082" geometry={nodes.Mesh082.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh082_1" geometry={nodes.Mesh082_1.geometry} material={materials.white_ambient_light} />
      </group>
      <group name="cake-slice-decoration002" rotation={[0, 1.2, 0]}>
        <mesh name="Mesh082" geometry={nodes.Mesh082.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh082_1" geometry={nodes.Mesh082_1.geometry} material={materials.white_ambient_light} />
      </group>
      <group name="cake-slice-decoration003" rotation={[-Math.PI, 0.68, -Math.PI]}>
        <mesh name="Mesh082" geometry={nodes.Mesh082.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh082_1" geometry={nodes.Mesh082_1.geometry} material={materials.white_ambient_light} />
      </group>
      <group name="cake-slice-decoration004" rotation={[Math.PI, -0.58, Math.PI]}>
        <mesh name="Mesh082" geometry={nodes.Mesh082.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh082_1" geometry={nodes.Mesh082_1.geometry} material={materials.white_ambient_light} />
      </group>
      <group name="outer-structure-side-lights" rotation={[0, -1.26, 0]}>
        <mesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials.white_ambient_light} />
      </group>
      <group name="outer-structure-side-lights002" rotation={[0, 1.26, 0]}>
        <mesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials.white_ambient_light} />
      </group>
      <group name="outer-structure-side-lights003" rotation={[-Math.PI, Math.PI / 5, -Math.PI]}>
        <mesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials.white_ambient_light} />
      </group>
      <group name="outer-structure-side-lights004" rotation={[Math.PI, -Math.PI / 5, Math.PI]}>
        <mesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials.white_ambient_light} />
      </group>
      <mesh name="outer-structure-lamps" geometry={nodes['outer-structure-lamps'].geometry} material={materials['main-metal-reflective']} rotation={[0, -1.26, 0]} />
      <group name="outer-structure-vents" rotation={[0, -1.26, 0]}>
        <mesh name="Mesh007" geometry={nodes.Mesh007.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh007_1" geometry={nodes.Mesh007_1.geometry} material={materials.white_ambient_light} />
      </group>
      <mesh name="outer-structure-over-vents" geometry={nodes['outer-structure-over-vents'].geometry} material={materials['main-metal-reflective']} rotation={[0, -1.26, 0]} />
      <mesh name="outer-structure-over-vents001" geometry={nodes['outer-structure-over-vents001'].geometry} material={materials['main-metal-reflective']} />
      <mesh name="outer-structure-over-vents002" geometry={nodes['outer-structure-over-vents002'].geometry} material={materials['main-metal-reflective']} rotation={[0, 1.26, 0]} />
      <mesh name="outer-structure-over-vents003" geometry={nodes['outer-structure-over-vents003'].geometry} material={materials['main-metal-reflective']} rotation={[-Math.PI, Math.PI / 5, -Math.PI]} />
      <mesh name="outer-structure-over-vents004" geometry={nodes['outer-structure-over-vents004'].geometry} material={materials['main-metal-reflective']} rotation={[Math.PI, -Math.PI / 5, Math.PI]} />
      <mesh name="outer-structure-pipes" geometry={nodes['outer-structure-pipes'].geometry} material={materials['main-metal-reflective']} rotation={[0, -1.26, 0]} />
      <mesh name="outer-structure-pipes001" geometry={nodes['outer-structure-pipes001'].geometry} material={materials['main-metal-reflective']} />
      <mesh name="outer-structure-pipes002" geometry={nodes['outer-structure-pipes002'].geometry} material={materials['main-metal-reflective']} rotation={[0, 1.26, 0]} />
      <mesh name="outer-structure-pipes003" geometry={nodes['outer-structure-pipes003'].geometry} material={materials['main-metal-reflective']} rotation={[-Math.PI, Math.PI / 5, -Math.PI]} />
      <mesh name="outer-structure-pipes004" geometry={nodes['outer-structure-pipes004'].geometry} material={materials['main-metal-reflective']} rotation={[Math.PI, -Math.PI / 5, Math.PI]} />
      <group name="pipe-decoration" rotation={[0, -1.31, 0]}>
        <mesh name="Mesh010" geometry={nodes.Mesh010.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh010_1" geometry={nodes.Mesh010_1.geometry} material={materials['main-metal-reflective']} />
      </group>
      <group name="pipe-decoration001" rotation={[0, -0.05, 0]}>
        <mesh name="Mesh010" geometry={nodes.Mesh010.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh010_1" geometry={nodes.Mesh010_1.geometry} material={materials['main-metal-reflective']} />
      </group>
      <group name="pipe-decoration002" rotation={[0, 1.2, 0]}>
        <mesh name="Mesh010" geometry={nodes.Mesh010.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh010_1" geometry={nodes.Mesh010_1.geometry} material={materials['main-metal-reflective']} />
      </group>
      <group name="pipe-decoration003" rotation={[-Math.PI, 0.68, -Math.PI]}>
        <mesh name="Mesh010" geometry={nodes.Mesh010.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh010_1" geometry={nodes.Mesh010_1.geometry} material={materials['main-metal-reflective']} />
      </group>
      <group name="pipe-decoration004" rotation={[Math.PI, -0.58, Math.PI]}>
        <mesh name="Mesh010" geometry={nodes.Mesh010.geometry} material={materials['main-metal-reflective']} />
        <mesh name="Mesh010_1" geometry={nodes.Mesh010_1.geometry} material={materials['main-metal-reflective']} />
      </group>
      <mesh name="Mesh036" geometry={nodes.Mesh036.geometry} material={materials['main-metal-reflective']} />
      <mesh name="Mesh036_1" geometry={nodes.Mesh036_1.geometry} material={materials.white_ambient_light} />
      <mesh name="Mesh054" geometry={nodes.Mesh054.geometry} material={materials['main-metal-reflective']} />
      <mesh name="Mesh054_1" geometry={nodes.Mesh054_1.geometry} material={materials.white_ambient_light} />
      <mesh name="Mesh055" geometry={nodes.Mesh055.geometry} material={materials['main-metal-reflective']} />
      <mesh name="Mesh055_1" geometry={nodes.Mesh055_1.geometry} material={materials.white_ambient_light} />
      <mesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials['main-metal-reflective']} />
      <mesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials.white_ambient_light} />
    </group>
  )
}

useGLTF.preload('/hq-v19-transformed.glb')
