/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -Tk logo.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/logo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Logo" geometry={nodes.Logo.geometry} material={nodes.Logo.material} position={[0, 6.04, 0]} rotation={[Math.PI / 2, 0, 0]} scale={12.81} />
    </group>
  )
}

useGLTF.preload('/logo-transformed.glb')
