/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -Tk pig_rigged.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/pig_rigged-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="MOOOOOVE">
          <group name="Pig_rig" position={[0.35, 0.51, 0.87]}>
            <primitive object={nodes.spine002} />
            <primitive object={nodes.pelvisL} />
            <primitive object={nodes.pelvisR} />
            <group name="yeballs_white006">
              <skinnedMesh name="Sphere040" geometry={nodes.Sphere040.geometry} material={materials['Material.003']} skeleton={nodes.Sphere040.skeleton} />
              <skinnedMesh name="Sphere040_1" geometry={nodes.Sphere040_1.geometry} material={materials['Material.006']} skeleton={nodes.Sphere040_1.skeleton} />
              <skinnedMesh name="Sphere040_2" geometry={nodes.Sphere040_2.geometry} material={materials['Material.007']} skeleton={nodes.Sphere040_2.skeleton} />
              <skinnedMesh name="Sphere040_3" geometry={nodes.Sphere040_3.geometry} material={materials['Material.008']} skeleton={nodes.Sphere040_3.skeleton} />
              <skinnedMesh name="Sphere040_4" geometry={nodes.Sphere040_4.geometry} material={materials.Metal} skeleton={nodes.Sphere040_4.skeleton} />
              <skinnedMesh name="Sphere040_5" geometry={nodes.Sphere040_5.geometry} material={materials['Astronaout white']} skeleton={nodes.Sphere040_5.skeleton} />
              <skinnedMesh name="Sphere040_6" geometry={nodes.Sphere040_6.geometry} material={materials.Material__41} skeleton={nodes.Sphere040_6.skeleton} />
            </group>
          </group>
          <mesh name="PIg_Body023" geometry={nodes.PIg_Body023.geometry} material={materials['Astronaout white']} position={[0.35, 2.84, 0.87]} />
          <skinnedMesh name="Eye_Lid_lower_L" geometry={nodes.Eye_Lid_lower_L.geometry} material={materials['Material.003']} skeleton={nodes.Eye_Lid_lower_L.skeleton} />
          <skinnedMesh name="Eye_Lid_lower_R" geometry={nodes.Eye_Lid_lower_R.geometry} material={materials['Material.003']} skeleton={nodes.Eye_Lid_lower_R.skeleton} />
          <skinnedMesh name="Eye_Lid_upper_L" geometry={nodes.Eye_Lid_upper_L.geometry} material={materials['Material.003']} skeleton={nodes.Eye_Lid_upper_L.skeleton} />
          <skinnedMesh name="Eye_Lid_upper_R" geometry={nodes.Eye_Lid_upper_R.geometry} material={materials['Material.003']} skeleton={nodes.Eye_Lid_upper_R.skeleton} />
          <skinnedMesh name="yeballs_white004" geometry={nodes.yeballs_white004.geometry} material={materials.eyebrows} skeleton={nodes.yeballs_white004.skeleton} />
          <skinnedMesh name="yeballs_white010" geometry={nodes.yeballs_white010.geometry} material={materials.eyebrows} skeleton={nodes.yeballs_white010.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pig_rigged-transformed.glb')
